### PR TITLE
Links and buttons

### PR DESCRIPTION
**Pull request by Studio28**
Styled buttons, wired up relevant links and added favicon.

### CODE REVIEW

**Comment by dopry** [comment]
1. target="blank" should be target _blank
2. mailto: links not working in firefox and chrome.
3. The contrast between the foreground and background doesn't work, please use the colors from the theme online. http://jspwcr.com/bs-harp/a.html  The text is all but invisible in most cases.
4. Put Visit our store on ebay first in the list of buttons. The call to action should always be the most prominent item. 
5. Social Links do not work. 
6. CNAME is not setup.

**Comment by Studio28** [comment]
In the latest commit, I fixed target = blank and the order of the CTA's on
the page.

As far as text and backgrounds, I can see all the text without any problem
so I'm not sure what you mean. If we go with the base colors for the theme,
they will be totally unrelated to the branding colors in her logo, but I
will revert to them if you think it 's better than what's there now.

I have been developing and testing in Firefox and Chrome and the mailto
links work fine in those browsers for me. I'll try and reproduce that issue
so I can address it. Is there anything you can see in that code that would
cause them to break when you're using them?

I know that the social links don't work, so I will email Tammy to see if
she has social network links we can use in the nav and footer. If not, I'll
find something to put there so there's not so much unused space in that
area.

**Comment by Studio28** [comment]
BTW, I was planning to setup CNAME when the site is ready to go live.

**Comment by Studio28** [comment]
I reverted some of the background colors to their default and it is a bit
more readable at those settings. I'll replace the social network links with
her 800 number for now.

**Comment by dopry** [comment]
Please update this pull request to reflect all the noted issues.

**Comment by dopry** [comment]
Where are you getting your colors?

Please use backgrounds that match those in the templates for the sections.
look at http://jspwcr.com/bs-harp/b.html and the t-n-c global site side by side.

1. The saturation on the header in the template is much richer than the one on the TNC site. Please find a color with a similar saturation so it won't look so washed out. 

2. Turn up the saturation on the red buttons a bit, they're too washed out.

3. In the template the third section does not repeat the purple background it uses a light grey. Please follow the template.

4. Be mindful of the styling for the button in the panes with the lighter grey background... Deeper saturation and darker borders, the orange one is dark bordered on the bottom creating a drop shadow effect. 


Overall we'll probably want to increase the saturation of the entire page. Noticed the increase saturation from the default header logo to the TNC logo. The presence of those colors and text makes the rest of the page seem super muted by comparison.

**Comment by Studio28** [comment]
The background colors are back to the defaults and the buttons and links are more deeply saturated.

**Comment by dopry** [comment]
This is a good step in the right direction.

1. I think we can keep the blue, for the banner, but should find a more
vibrant blue... maybe this one, #79c6fc.
2. Let's remove email us and learn more from the jumbo tron. It doesn't
link to content so it doesn't make sense for it to go anywhere yet. I don't
think tammy has the over head to be managing a lot of incoming email. I
think the email us button can wait for a mailchimp list setup.
3. Let's make visit out ebay store green.
4. Let's remove the 3rd section all together and, it isn't really adding
any value, just re-iterating the jumbotron.




On Wed, Aug 12, 2015 at 5:43 PM, Ted <notifications@github.com> wrote:

> The background colors are back to the defaults and the buttons and links
> are more deeply saturated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/t-n-c-global/t-n-c-global.github.io/pull/2#issuecomment-130457380>
> .
>



-- 
Darrel O'Pry
The Spry Group, LLC.
http://www.spry-group.com
718-355-9767 x101

**Pull request merged**
